commit #28 final fixing

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -22,17 +22,11 @@ phases:
   pre_build:
     commands:
       - echo "Logging into ECR..."
-      - aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin 834549009763.dkr.ecr.us-east-1.amazonaws.com || { echo "ECR login failed"; exit 1; }
+      - aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin 834549009763.dkr.ecr.us-east-1.amazonaws.com || echo "ECR login failed"
       - echo "Creating S3 bucket to store dkcfg to be deployed by Beanstalk..."
-      - |
-        if ! aws s3api head-bucket --bucket $AWS_BUCKET_NAME 2>/dev/null; then
-          echo "Bucket does not exist. Creating bucket..."
-          aws s3 mb s3://$AWS_BUCKET_NAME || { echo "Failed to create S3 bucket"; exit 1; }
-        else
-          echo "Bucket already exists. Skipping creation."
-        fi
-      - aws s3 cp dkcfg s3://$AWS_BUCKET_NAME || { echo "Failed to upload dkcfg"; exit 1; }
-      - aws s3 cp Dockerrun.aws.json s3://$AWS_BUCKET_NAME || { echo "Failed to upload Dockerrun.aws.json"; exit 1; }
+      - aws s3 mb s3://$AWS_BUCKET_NAME || echo "Bucket already exist or failed to create"
+      - aws s3 cp dkcfg s3://$AWS_BUCKET_NAME || echo "Failed to upload dkcfg"
+      - aws s3 cp Dockerrun.aws.json s3://$AWS_BUCKET_NAME || echo "Failed to upload Dockerrun.aws.json"
 
   build:
     commands:
@@ -43,7 +37,7 @@ phases:
   post_build:
     commands:
       - echo "Pushing the image to ECR..."
-      - docker tag lks-catalog/bebyschalke:latest 834549009763.dkr.ecr.us-east-1.amazonaws.com/lks-catalog/bebyschalke:latest || { echo "Failed to tag Docker image"; exit 1; }
+      - docker tag lks-catalog/bebyschalke:latest 834549009763.dkr.ecr.us-east-1.amazonaws.com/lks-catalog/bebyschalke:latest || echo "Failed to tag Docker image"
       - docker push 834549009763.dkr.ecr.us-east-1.amazonaws.com/lks-catalog/bebyschalke:latest || { echo "Failed to push Docker image to ECR"; exit 1; }
       - echo "Image has been pushed into ECR..."
       - printf '[{"name":"%s","imageUri":"%s "}]' $CONTAINER_NAME ${ECR_REPO}:latest > imagedefinitions.json
